### PR TITLE
Update ndk, openssl, libevent, tor, bitcoin and elements

### PR DESCRIPTION
**Pull request by greenaddress**

### CODE REVIEW

**Comment by udiWertheimer** [comment]
ack fee64ab

**Comment by greenaddress** [comment]
this also updates core from v0.18.0 to https://github.com/bitcoin/bitcoin/compare/v0.18.0...v0.18.1rc1

**Comment by lvaccaro** [comment]
ack 2c07670530d6d1f6080252b9f0c38eda12184dfa

**Comment by udiWertheimer** [comment]
ack f9b056f

**Pull request merged**
